language: go
go: '1.12.x'

addons:
  apt:
    packages:
      - rpm
      - snapd

env:
  - PATH=/snap/bin:$PATH

install:
  - sudo snap install snapcraft --classic

services:
  - docker

after_success:
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
